### ISSUE TITLE
Better name for "Verbose display mode" 

### ISSUE THREAD

**Issue by inson1** [artyommironov/nanji#12]
Is there reason? Because all "Verbose display mode" is doing is using words and not numbers.

@artyommironov Btw sorry if I'm spamming you

**Comment by artyommironov** [comment]
"verbose" means "wordy" and "verbal" means "spoken". Both numbers and words can be spoken so "verbal" doesn't fit here, isn't it? Technically if we don't count numbers as words then it means we show more words, so "verbose" make sense. But I think it's not a perfect case for usual meaning of "verbose". In old version this mode was called like "Show words" but I thought it might be unlear to users. Maybe there are other options? BTW I can be wrong, because English is not my native language.

**Comment by inson1** [comment]
Yea english isnt my native language either, so its hard to come up with replacement, but "verbose" means "by the use of many or too many words"  and that i think just doesnt explain it very well.
Yea you right, "verbal" isnt great option for replacement, but it also means "consisting of words" and "communication with words" and that was my line of thinking. 

I would let this issue open for while if someone doesnt get better idea, but in last case scenario I would just replace it with "Time with numbers/words" or something like that imo.

**Comment by inson1** [comment]
@artyommironov What about "Replace numbers with words" its easy, clear etc.

**Comment by Vsnmrn** [comment]
Thank you @inson1 ^^ I decided to translate the string like this by reading this issue!

However, I wondered how to translate "toggle verbose display mode" given that "toggle replace numbers by words" does not sound good. In my translation I have finally chosen "toggle words display mode" but I’m not sure the link between the two options is clear. I thought about it and now I think "switch between numbers and words" would be clearer. What do you think?

**Comment by inson1** [comment]
@Vsnmrn Well I'm happy that this issue helped, even If I didnt come up with something better. You should have said something, if you read this and got an idea. At least I and Google translate did find it. 😃

Yes that is also better. Btw I think that "toggle between numbers and words" is maybe even better imho. What do you think? 

And if you would prefer translate in weblate/crowdin, please like this issue #26.

**Comment by Vsnmrn** [comment]
Yes, clearly I wonder why I didn't do it. 

@inson1 I trust you, in the context in which it is used, switch and between have the same translation into French anyway. But it is true that "toggle" may be better than "switch". 

I have already made the change in my translation. If @artyommironov thinks it's not suitable, I can change it later of course. 

Indeed, Weblate would probably be easier to use and could allow more people to contribute.

**Comment by artyommironov** [comment]
> Replace numbers with words

Word "replace" was used in the past, but it was changed because it's not just "replace numbers with words" but rather a different mode. Not only numbers will be replaced and extra words might be added. For example "00:00" is "Zero hundred" (English military form). `:` is not a number, and `hundred` came out of nothing. And the might be more cases as new supported languages are added.
So I'm thininking of something like "Words instead of numbers". No need extra verb like "Use" or "replace" because switch UI control is alreaydy implying "use/activate/enable". What do you think?

> toggle between numbers and words

How about shorter "Toggle words/numbers"?

**Comment by Vsnmrn** [comment]
Oh, okay, I wasn't aware of this subtlety. So we should avoid "replace"…

On second thoughts, I'm not convinced by "words display mode" because as I mentioned earlier I think that "words display mode" does not really describe what the option do. 
However, if we assume that a verb is not necessary, I think "words instead of numbers" is a good proposal. @inson1 what do you think?

Toggle words/numbers
As is often the case, the shorter the better! However, if we decide to use this wording it will not change my translation (which would not sound good if I translated "toggle words/numbers" literally). But this is ultimately only a detail, the important thing is to find the best wording in English to have a good basis for future translations, and I think @artyommironov found something good.
