### ISSUE TITLE
Would you please add another clock ComponentName?

### ISSUE THREAD

**Issue by revuwa** [artyommironov/nanji#2]
Would you add another clock app:

- "com.better.alarm"
source: https://github.com/yuriykulikov/AlarmClock

to your WidgetProvider.kt, please?

By the way, I saw another widget-app, which opens my alarm app onClick, while it isn't explicit specified.
If you're interested, I think it's the "RC_OPEN_CLOCK" part from here:
https://github.com/ashutoshgngwr/10-bitClockWidget/blob/master/10-bitClockWidget/app/src/main/java/com/github/ashutoshgngwr/tenbitclockwidget/ClockWidgetProvider.java

But I'm not sure, because I don't have adequate developing skills.
Probably, it helps at least to inspire you a bit :-)

**Comment by kazufukurou** [comment]
Thanks for letting me know of a new way. I think it's better than current hard-coded way, though it has few downsides:
- show alarm screen instead of clock screen
- show set alarm screen on pre KitKat devices
- requires extra manifest permission

But anyway, alarm and clock are usually in same app, and very few users use such old devices. I installed mentioned clock app and tried new method, but it still opens system alarm app. Did you do some additional steps to make it open non-system alarm app?

**Comment by revuwa** [comment]
Sorry for (too) laaate response and thanks a lot for looking into this.

> Did you do some additional steps to make it open non-system alarm app?

No.

Meanwhile I switched to another clock app (https://github.com/qw123wh/Aospdeskclock) which works, (because deskclock is known) with your way to open the clock app. Thanks again for your great app, which is very helpful 👍
